---

# Application settings.
project_path: "/home/{{ project_name }}"
application_path: "{{ project_path }}/www/{{ project_name }}"
virtualenv_path: "{{ project_path }}/www/venv"

project_log_dir: "{{ project_path }}/logs"
project_conf_dir: "{{ project_path }}/conf"
requirements_file: "{{ application_path }}/requirements.txt"
requirements_extra: "{{ application_path }}/requirements.extra"

vassals_path: "/etc/uwsgi/vassals"

