---
  - name: Install additional packages
    become: no
    pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}/{{ extra_python_packages }}
    when: extra_python_packages is defined


  - name: Install packages required by the Django app inside virtualenv
    become: no
    pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

  - name: Read list of extra system packages to install
    shell: "cat {{ application_path }}/{{ extra_apt }}"
    register: command_result
    when: extra_apt is defined  

  - name: Install additional system packages
    apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
    with_items: "{{command_result.stdout_lines}}"
    when: command_result is defined  
