---
  - name: Install additional packages
    become_user: "{{ system_user }}"
    become: yes
    become_method: sudo
    pip: virtualenv={{ virtualenv_path }} requirements={{ application_path }}/{{ extra_python_packages }}
    when: extra_python_packages is defined


  - name: Install packages required by the Django app inside virtualenv
    become_user: "{{ system_user }}"
    become: yes
    become_method: sudo
    pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

  - name: Install additional system packages
    become_user: "{{ system_user }}"
    become: yes
    become_method: sudo
    shell: name={{ application_path }}/{{ extra_install }}
           creates={{ application_path }}/{{ extra_install }}.done
    tags: packages
    when: extra_install is defined