---

- name: Create directory for ssh keys
  become: no
  file:
    name: "~/.ssh"
    owner: "{{ deployman }}"
    group: "{{ deployman }}"
    state: directory
  no_log: False
  tags: deploy

- name: check deployment private key exists
  local_action: stat path="roles/deploy/files/secret.key"
  become: no
  register: private_exists 
  tags: deploy

- name: copy deployment private key
  become: no
  copy:
    src: "secret.key"
    dest: "~/.ssh/id_rsa"
    owner: "{{ deployman }}"
    group: "{{ deployman }}"
    mode: 0600
  when: private_exists is defined and private_exists.stat.exists
  tags: deploy

- name: check deployment private key exists
  local_action: stat path="roles/deploy/files/public.key"
  become: no
  register: public_exists 
  tags: deploy

- name: copy deployment public key
  become: no
  copy:
    src: "public.key"
    dest: "~/.ssh/id_rsa.pub"
    owner: "{{ deployman }}"
    group: "{{ deployman }}"
    mode: 0600
  when: public_exists is defined and public_exists.stat.exists
  tags: deploy

- include: setup_git_repo.yml
  tags: deploy

- include: set_file_permissions.yml

- include: install_requirements.yml
  tags: deploy

- name: Ensure that the virtualenv file permissions are set properly
  file: 
      path: "{{ virtualenv_path }}"
      owner: "{{ system_user }}"
      group: "{{ system_group }}"
      recurse: yes
      mode: u=rwX,g=rw,o=rw

- include: setup_django_app.yml
  become: yes
  become_method: sudo
  become_user: "{{ system_user }}"
  notify: touch reload
  tags: deploy

