---

- name: Create directory for ssh keys
  file:
    name: "/home/{{ system_user }}/.ssh"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    state: directory
  no_log: False
  tags: deploy

- name: check deployment private key exists
  local_action: stat path="roles/deploy/files/secret.key"
  register: private_exists 
  tags: deploy

- name: copy deployment private key
  copy:
    src: "secret.key"
    dest: "/home/{{ system_user }}/.ssh/id_rsa"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0600
  when: private_exists is defined and private_exists.stat.exists
  tags: deploy

- name: check deployment private key exists
  local_action: stat path="roles/deploy/files/public.key"
  register: public_exists 
  tags: deploy

- name: copy deployment public key
  copy:
    src: "public.key"
    dest: "/home/{{ system_user }}/.ssh/id_rsa.pub"
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: 0600
  when: public_exists is defined and public_exists.stat.exists
  tags: deploy

- include: setup_git_repo.yml
  tags: deploy

- include: install_requirements.yml
  tags: deploy

- include: setup_django_app.yml
  become: true
  become_method: su
  become_user: "{{ system_user }}"
  notify: touch reload
  tags: deploy

