---

- name: Ensure that the application file permissions are set properly
  file: 
      path: "{{ application_path }}"
      owner: "{{ system_user }}"
      group: "{{ system_group }}"
      recurse: yes
      mode: u=rwX,g=rwX,o=rX

- name: Set the virtualenv file permissions to deployman
  file: 
      path: "{{ virtualenv_path }}"
      owner: "{{ deployman }}"
      group: "{{ deployman }}"
      recurse: yes
      mode: u=rwX,g=rw,o=rw


