---

- name: Add required sites with repos in known_hosts
  sudo: yes
  sudo_user: "{{ system_user }}"
  known_hosts: path="{{ project_path }}/.ssh/known_hosts"
               name="{{ item }}"
               state=present
               key="{{ lookup('file', '{{ item }}') }}"
  with_items:
    - github.com
    - bitbucket.com

- name: Add required sites with repos in known_hosts
  sudo: yes
  sudo_user: "{{ system_user }}"
  known_hosts: path="{{ project_path }}/.ssh/known_hosts"
               name="{{ item }}"
               state=present
               key="{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item }}') }}"
  with_items: known_hosts
  when: known_hosts is defined



- name: Setup the Git repos and submodules (as separate repos)
  sudo: yes
  sudo_user: "{{ system_user }}"
  git: repo={{ item.repo }}
       version="{{ item.branch }}"
       dest="{{ application_path }}/{{ item.dest }}"
       accept_hostkey=yes
       update=yes
       recursive=no
       force=yes
       track_submodules=no
       key_file="{{ project_path }}/.ssh/id_rsa"
  with_items: git_repos
  when: setup_git_repo is defined and setup_git_repo
  tags: git


- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ application_path }}"
  tags: git

- name: Ensure that the application file permissions are set properly
  file: path={{ application_path }}
        recurse=yes
        owner={{ system_user }}
        group={{ system_group }}
        state=directory
  notify: restart application
