---
- name: Create local settings
  template: src=local_settings.py.j2
            dest={{ application_path }}/{{ application_name }}/local_settings.py
            backup=yes

- name: Ensure that the application dir permissions are set properly
  file: 
      path: "{{ application_path }}"
      recurse: yes
      owner: "{{ system_user }}"
      group: "{{ system_group }}"
      mode: u=rwX,g=rw,o=rw


- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ application_path }}"
    pythonpath: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"

  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ application_path }}"
    pythonpath: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic


- name: Load data from fixtures
  django_manage:
    command: loaddata
    fixtures: "{{ fixtures }}"
    app_path: "{{ application_path }}"
    pythonpath: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: fixtures is defined
  tags: django.migrate
