---

- name: Provision a db server
  hosts: dbservers
  become: yes
  become_user: root
  become_methon: su
  remote_user: root
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - db
