---

- name: Setup a {{ application_name }} server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  become_method: sudo
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    #- rabbitmq
    - web
    #- xapian
    - db
    - deploy
    #- celery
    #- backup
    #- glances
