---

- name: Setup a {{ application_name }} server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - rabbitmq
    - web
    - db
    - deploy
    - celery