---

- name: Update server
  hosts: all
  become: yes
  become_user: root
  become_methon: sudo
  remote_user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes  
  roles:
    - update
