---

- name: Update server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes  
  roles:
    - update