---

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart uwsgi
  service: name=uwsgi state=restarted enabled=yes

- name: reload uwsgi
  service: name=uwsgi state=reloaded

