---

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart uwsgi
  supervisorctl: name=master_uwsgi state=restarted

- name: reload uwsgi
  supervisorctl: name=master_uwsgi state=reloaded

