---

- name: restart postgresql
  service: name=postgresql state=restarted enabled=yes
  when: database is defined and database=="postgresql"

- name: restart mysql
  service: name=mysqld state=restarted enabled=yes
  when: database is defined and database=="mysql"
