---

- name: Create the application user
  user: name={{ system_user }} state=present

- name: Create the application group
  group: name={{ system_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ system_user }} group={{ system_group }} state=present

- name: Set user id variable
  command: id -u {{ system_user }}
  register: system_user_id

- name: Create the application folder
  file: path={{ application_path }}
        owner={{ system_user }}
        group={{ system_group }}
        mode=0775
        state=directory
