---

- name: Create the virtualenv
  sudo: yes
  sudo_user: "{{ system_user }}"
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: Create tmp folder
  file: path={{ project_path }}/tmp
        owner={{ system_user }}
        group={{ system_group }}
        mode=0774
        state=directory
