---

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate


- name: Create the application log folder
  file: path={{ project_log_dir }}
        owner={{ system_user }}
        group={{ system_group }}
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
           creates={{ application_log_file }}


- name: Create tmp folder
  file: path={{ project_path }}/tmp
        owner={{ system_user }}
        group={{ system_group }}
        mode=0774
        state=directory

- name: Set permission to the application log file
  file: path={{ application_log_file }}
        owner={{ system_user }}
        group={{ system_group }}
        mode=0664
        state=file

- name: Create the maintenance page
  template: src=maintenance_off.html
            dest={{ virtualenv_path }}/maintenance_off.html
            mode=0664
