---

server_root_dir: /home/{{ application_name }}

virtualenv_path: "{{ server_root_dir }}/www/venv"
project_path: "{{ server_root_dir }}/www/{{ project_name }}"

celery_user: "{{ application_name }}"
celery_group: "{{ application_name }}"

celery_application_name: "celery_{{ application_name }}"
celery_beat_application_name: "celery_{{ application_name }}_beat"
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "celery_start.j2"

celery_log_dir: "{{ server_root_dir }}/logs"
celery_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}.log"
celery_beat_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}_beat.log"
